# Generated by Django 4.2.7 on 2023-11-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_delete_skill_remove_resume_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='jobRole',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
    ]
